name: pg

image: postgres:10.5

nodeSelector:
  cloud.google.com/gke-nodepool: pg

replicas: 1

resources:
  requests:
    memory: 10Gi
  limits:
    memory: 12Gi

pvc:
- name: data
  class: ssd
  size: 500Gi
  mountPath: /var/lib/postgresql/data/

env:
- name: BACKUP
  value: "true"

configmaps:
- name: postgresql.conf
  value: |
    # Connectivity
    max_connections = 500
